### PR TITLE
Add some information about convex and triangle mesh collision data.

### PR DESCRIPTION
**Pull request by MineBill**
This adds some information and images explaining what the Type property of collision data does and makes a remark about the usage of triangle mesh with Rigidbodies. It *should* help with some of the confusion people have when they add a mesh collider to their Rigidbodies.
Here is a preview:
image

### CODE REVIEW

**Comment by Menotdan** [comment]
I think the final statement about rigidbodies is a bit confusing. Maybe something like "Cannot be used while attached to a rigidbody. Collisions still work against a rigidbody, though." but not sure.

**Comment by MineBill** [comment]
How about "Cannot be use to provide collision for a Rigidbody." And remove the second part of the sentence altogether.

**Comment by d1kkop** [comment]
Perhaps also set convex as the default, so when adding a rigid body with a custom mesh it actually drops on the floor.

**Comment by Menotdan** [comment]
> Perhaps if, a rigid body is the parent, then set the default to convex instead of triangular mesh, as one expects it to collide. I would say: Cannot be used with rigidbodies.

Well, it can be used with rigidbodies, just not as the collider that the rigidbody controls.

**Comment by mafiesto4** [comment]
I merged it and did a minor cleanup of working in ffebe7940956688b084942eff660e0682ef8fd84, Thanks!

**Pull request merged**
